### ISSUE TITLE
Add libraries to J2Objc classpath

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#6]
I tried to add the realtime-json lib to J2Objc https://github.com/goodow/realtime-json
``realtime-json-0.5.5-SNAPSHOT-sources.jar`` is under ``${projectDir}/lib/``

Here is my config: 

```
j2objcConfig {
 j2objcHome "/Applications/J2Objc/j2objc-0.9.6" 
 destDir "${projectDir}/../number-incrementer-ios/Classes"

translateFlags "--no-package-directories --prefixes prefixes.properties --mapping method-mappings.properties -use-arc -classpath ${projectDir}/lib/realtime-json-0.5.5-SNAPSHOT-sources.jar"

compileFlags "-ObjC -ljre_emul"

translateJ2objcLibs "guava-14.0.1.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"

filenameCollisionCheck = true
	testExecutedCheck = false

}
```

I does not compile (``gradle j2objcTranslate``). I get the following errors: 

```
Script '/Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/j2objc.gradle' line: 328

* What went wrong:
Execution failed for task ':j2objcTranslate'.
> Process 'command '/Applications/J2Objc/j2objc-0.9.6/j2objc'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':j2objcTranslate'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Applications/J2Objc/j2objc-0.9.6/j2objc'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:151)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:792)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:788)
	at org.gradle.api.Project$exec$4.call(Unknown Source)
	at J2objcTranslateTask.translate(/Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/j2objc.gradle:328)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 44 more


BUILD FAILED
```

I suppose there is something wrong with my declaration of classpath?

**Comment by brunobowden** [comment]
Add the "--info" flag on gradle to find out what command it's running. It's
much faster to experiment on this using the j2objc command outside of
gradle... then also switch j2objc to javac to help further. I should fix it
up though that a translate failure like this outputs stderr to help
understand the bug.

**Comment by confile** [comment]
Did I set the parameter correctly?

**Comment by brunobowden** [comment]
Can't tell easily. This looks like a j2objc error that the gradle script is
hiding. Using --info and then running the j2objc script outside of gradle
should reveal the issue.

**Comment by confile** [comment]
Here is it: 

```
error: /Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/src/main/java/com/example/incrementer/shared/JSNIExample.java:3: The import com.goodow.realtime.json.JsonObject cannot be resolved
error: /Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/src/main/java/com/example/incrementer/shared/JSNIExample.java:14: JsonObject cannot be resolved to a type
```

Looks like the configuration was wrong. Could you please give me an example how it is correct or correct my example?

**Comment by brunobowden** [comment]
If you replace j2objc with javax does it compile successfully? Tom usually
recommends starting with that.

Once you've done that, I'd suggest asking on the j2objc-discuss mailing
list as this is outside what I know.

**Comment by confile** [comment]
You wrote in your comments that everything you add to translateFlags you have to add to compileFlags

So what is the syntax for doing that?

**Comment by brunobowden** [comment]
Just add another line to j2objcConfig. Duplicate the translateFlags line
and then rename the copy as compileFlags.

Can you file another issue to have compileFlags re-use translateFlags.
That'll make it easier to avoid mistakes.

**Comment by brunobowden** [comment]
Confile, thinking about it that sounds wrong... can you point me to that
comment? Translate and compile are two different stages so should have
different flags.

**Comment by brunobowden** [comment]
I'm in an Uber late for a meeting so I don't have more time to spend on
this right now.

**Comment by confile** [comment]
Sorry I mean Translate we are talking about this command here: 

 ``gradle j2objcTranslate``

**Comment by confile** [comment]
I create a new fresh issue

**Comment by confile** [comment]
Lets clean this up here: https://github.com/brunobowden/j2objc-gradle/issues/7
